githubConfigUrl: https://github.com/appstuio
githubConfigSecret: arc-github-config
runnerScaleSetName: byo
minRunners: 1
maxRunners: 8

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/appstuio/runner:latest@sha256:999c87dfbf5a8325fab5f9f1618599c20e05aad157da6c5f81feabfd6b3180d5
        imagePullPolicy: IfNotPresent
        command:
          - /home/runner/run.sh
        resources:
          limits:
            cpu: "1"
            memory: 1536Mi
          requests:
            cpu: 750m
            memory: 1536Mi
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
    volumes:
      - name: work
        emptyDir: {}
