githubConfigUrl: https://github.com/appstuio
githubConfigSecret: arc-github-config
runnerScaleSetName: byo
minRunners: 1
maxRunners: 8

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/appstuio/runner:latest@sha256:bc93be1f1c651c50857ed22360466f7c7d277ae6f80f922ee9375bdff05324df
        imagePullPolicy: IfNotPresent
        command:
          - /home/runner/run.sh
        resources:
          limits:
            cpu: "1"
            memory: 1536Mi
          requests:
            cpu: 750m
            memory: 1536Mi
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
    volumes:
      - name: work
        emptyDir: {}
